config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/signup', to: 'users#new', as: 'signup'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/recipes/order_by_name', to: 'recipes#name'
  get '/users/:id/recipes/order_by_name', to: 'recipes#myname', as: 'ordered'
  get '/recipes/recently_updated', to: 'recipes#updated'

  resources :quantities
  resources :ingredients
  resources :recipes

  resources :users, only: [:new, :create, :show] do
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  get 'ajaxland', to: 'recipes#ajaxland'
  # post 'ajaxland', to: 'recipes#ajaxland'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :quantities
  has_many :recipes, through: :quantities

end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient


  def name
    self.ingredient.name if self.ingredient
  end

  def name=(name)
    self.ingredient = Ingredient.find_or_create_by(name: name)
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :quantities
  has_many :ingredients, through: :quantities

  validates :name, presence: true
  validates :description, presence: true
  validates :instructions, presence: true

  # scope :order_by_name, -> {order('lower(name) ASC')}
  def self.order_by_name
    order('lower(name) ASC')
  end

  def quantities_attributes=(quantities_attributes)
    quantities_attributes.values.each do |quantity_attributes|
      unless quantity_attributes[:name].blank?
        quantity = Quantity.new(quantity_attributes)
        self.quantities << quantity
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true, length: { in: 6..100 }

  has_secure_password

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
        user.password = SecureRandom.hex
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user, :require_login
  
  private

  def current_user
    if session[:user_id]
      @current_user || User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section."
      redirect_to login_path
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredient = Ingredient.find_by(id: params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login
  # skip_before_action :require_login, only: [:index]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def ajaxland
  end

  def index
    if params[:user_id]
      @user = current_user
      @recipes = @user.recipes
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @recipes}
      end
    else
      @recipes = Recipe.all
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @recipes}
      end
    end
  end

  def new
    @recipe = Recipe.new
    4.times{@recipe.quantities.build}
    if params[:layout] && params[:layout] == 'false'
      render :new, layout: false
    else
      render :new
    end
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      # redirect_to user_recipe_path(current_user.id, @recipe)
      render json: @recipe, status: 201
    else 
      # render :new
      render json: JSON.generate({error: "Invalid form entries"}), status: 400
    end
  end

  def show
    if !@recipe
      flash[:notice] = "Recipe does not exist."
      redirect_to recipes_path
    end
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @recipe}
    end
  end

  def edit
    @user = current_user
    if !@recipe
      flash[:notice] = "Recipe does not exist for this user."
      redirect_to recipes_path
    end
    add_quantity = 4 - @recipe.quantities.length
    add_quantity.times {@recipe.quantities.build}
  end

  def update
    @recipe.quantities.destroy_all
    if @recipe.update(recipe_params)
      redirect_to user_recipe_path(current_user.id, @recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.delete
    redirect_to recipes_path
  end

  def name
    @recipes = Recipe.order_by_name
  end

  def myname
    @user = current_user
    @recipes = @user.recipes.order_by_name
  end

  private

  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(
      :user_id, 
      :name, 
      :description, 
      :instructions, 
      quantities_attributes: [:name, :amount]
      )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      flash[:notice] = "You're logged in."
      redirect_to recipes_path
    else
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = current_user = @user.id
        flash[:notice] = "You're logged in."
        redirect_to recipes_path
      else 
        flash[:alert] = "Invalid username/password."
        render :new
      end
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have successfully logged out."
    redirect_to login_path
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully logged in."
      redirect_to recipes_path
    else 
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/show.html.erb
<h2>All Recipes with <%= @ingredient.name %>.</h2>
<ul>
<% @ingredient.recipes.each do |r| %>
  <li><%= link_to r.name, recipe_path(r) %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/_displayall.html.erb


<div class="container">
  <div class="row">
    <% recipes.each do |r| %>
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= r.name %></h5>
          <%= link_to "View", user_recipe_path(current_user.id, r), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <% end %>
 </div>
</div>

app/views/recipes/_errors.html.erb

  <% if recipe.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from saving:</h2>
      <ul>
        <% recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>

app/views/recipes/_form.html.erb
<%= render partial: 'recipes/errors', locals: {recipe: @recipe} %>

<div class="container">
  <%= form_for [user, recipe] do |f| %>
    <div class="form-group">
      <%= f.label "Name", class: "font-weight-bold" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label "Description", class: "font-weight-bold" %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <%= f.label "Ingredients", class: "font-weight-bold" %>
    <div class="form">
      <%= f.fields_for :quantities do |q| %>
        <%= q.label :amount, class: "font-weight-normal" %>
        <%= q.text_field :amount, class: 'form-control' %>
        <%= q.label :name, class: "font-weight-normal" %>
        <%= q.text_field :name, class: 'form-control' %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label "Instructions", class: "font-weight-bold" %>
      <%= f.text_area :instructions, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-primary', id: 'submit-form'%>
    </div>
  <% end %>
</div>

app/views/recipes/_nameorder.html.erb
<% if params[:user_id] %>
  <%= link_to "Sort by Name", ordered_path(current_user.id) %> 
<% else %>
  <%= link_to "Sort by Name", recipes_order_by_name_path %> 
<% end %>

app/views/recipes/ajaxland.html.erb
<h2>AJAX Land</h2>
<div style="float:left" id="ajax-content">
    <%# <div id="search_bar">
        <input type="text" name="search" value="" autocomplete="on"
        id="searchInput" onkeyup="searchRecipe" placeholder="Search">
    </div> %>
</div><br>


app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: {user: @user, recipe: @recipe} %>

app/views/recipes/index.html.erb

 <%= render partial: 'displayall', locals: {recipes: @recipes} %>

app/views/recipes/myname.html.erb
<%= render partial: 'displayall', locals: {recipes: @recipes} %>

app/views/recipes/name.html.erb
<%= render partial: 'displayall', locals: {recipes: @recipes} %>

app/views/recipes/new.html.erb
<h2>Create a 4 Recipe Meal</h2>

<%= render partial: 'form', locals: {user: @user, recipe: @recipe} %>

<%= link_to "Back", recipes_path, class: 'btn btn-secondary' %>

app/views/recipes/show.html.erb

<h3>Name: <%= @recipe.name %><br></h3>
<h4>Description: <%= @recipe.description %><br></h4>
  <h5><p>Ingredients:</h5> <% @recipe.quantities.each do |q| %></p>
    <p><%= q.amount %> <%= link_to q.ingredient.name, ingredient_path(q.ingredient) %></p>
  <% end %>
<h5>Instructions:</h5> <%= @recipe.instructions %><br>


<%= link_to "Back", recipes_path, class: 'btn btn-secondary' %>
<% if current_user == @recipe.user %>
  <%= link_to "Edit", edit_user_recipe_path(current_user, @recipe), class: 'btn btn-secondary' %>
  <%= form_tag recipe_path(@recipe), method: "delete", data: { confirm: "Are you sure you want to delete this item?" } do %>
    <%= submit_tag "Delete", class: 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">4 Recipe Book</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Logout", logout_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "AjaxLand", ajaxland_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "All Recipes", recipes_path, class: 'nav-link', id: 'all-recipes' %>
      </li>
      <li class="nav-item">
        <%= link_to "New Recipe", new_user_recipe_path(current_user.id), class: 'nav-link', id: 'new-recipe' %>
      </li>
      <li class="nav-item">
        <%= link_to "My Recipes", user_recipes_path(current_user.id), class: 'nav-link', id: 'my-recipes' %>
      </li>
        <% if params[:user_id] %>
          <li class="nav-item">
            <%= link_to "Sort by Name", ordered_path(current_user.id), class: 'nav-link' %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sort by Name", recipes_order_by_name_path, class: 'nav-link' %> 
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
        <%= link_to "Signup", signup_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Login", login_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<h2>Create an Account!</h2>

  <% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from saving:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>

<div class="container">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Sign Up", class: 'btn btn-primary' %><br>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center">Welcome</h1>
<h3 class="text-center">4 Recipe Book!</h3>